### ISSUE TITLE
Config not being set for multi-site project

### ISSUE THREAD

**Issue by ryaan-anthony** [workarea-commerce/workarea-google-address-autocomplete#1]
**Describe the bug**
After configuring the plugin, the autocomplete just shows an error: "This page can't load Google Maps correctly." with the JS error: `You must use an API key to authenticate each request to Google Maps Platform APIs.`

I checked to make sure it was configured:

from rails console:
`Workarea.config.google_address_autocomplete_api_key` is our api key

from JS console:
`WORKAREA.config.googleAddressAutocomplete['apiKey']` **is an empty string**

**Comment by tubbo** [comment]
are you seeing this locally as well when you start the server with `SITE_ID=your_site_id rails server`?

**Comment by ryaan-anthony** [comment]
It works as expected locally with and without the SITE_ID.

**Comment by JakeBeresford** [comment]
This issue is also affecting the workarea-store_locations plugin. Might be a bug with workarea-multi_site rather than these individual plugins?

**Comment by tubbo** [comment]
@JakeBeresford @ryaan-anthony do you have separate JS manifests configured for each site? if not, the `assets:precompile` task won't be able to change out the credentials when you switch to a different site.

you might want to check out the `workarea:site` generator, it automatically sets all of this up for you.

**Comment by tubbo** [comment]
This seems resolved, closing...
